$(document).ready(function(){
  //Lehe avamisel avab avalehe
  $("#keha").load("avaleht.html");
  //Menüü
  $("#avaleht").click(function(){
      $("#keha").empty();
      $("#keha").load("avaleht.html");
    });
	$("#statistika").click(function(){
  		$("#keha").empty();
    	$("#keha").load("statistika.html");
      setTimeout(function(){document.getElementById("statistika_tekst").style.visibility="hidden";},1500);
      setTimeout(function(){document.getElementById("chart_pie").style.visibility="visible";},1500);
      setTimeout(function(){document.getElementById("chart_div").style.visibility="visible";},1500);
  	});
	$("#user").click(function(){
		$("#keha").empty();
  	$("#keha").load("seaded.html");
	});
  $("#haaletamine").click(function(){
    $("#keha").empty();
    $("#keha").load("haaletamine.html");
  });
  $("#kandideeri").click(function(){
    $("#keha").empty();
    $("#keha").load("kandideeri.html");
  });
});